.\" Copyright (C) 2013 Niv Sardi <xaiki@debian.org>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH huayra-identinet 1 "2013\-02\-19" "Huayra"
.SH NAME
huayra-identinet-set \- Helper to set hostname
.SH SYNOPSIS
.B huayra-identinet-set new_hostname
.RI [ OPTION... ]
.SH DESCRIPTION
.B huayra-identinet-set
allows you to change the computer name (hostname) not only for the running
session, but also goes through the work to change everything that is needed
in /etc, and restart needed services
.SH OPTIONS
.TP
.B huayra-identinet-set
does not have any command line switches.
.SH AUTHORS
.B huayra-identinet-set
was written by Author Miguel Angel Garcia <miguelgarcia@anses.gov.ar> and others
.P
This manual page was written by Niv Sardi <xaiki@debian.org>,
for the Debian project (but may be used by others).
.SH SEE ALSO
.BR "huayra-identinet-set" (7).

